### ISSUE TITLE
com.google.cloud.datastore.DatastoreException: too much contention on these datastore entities. please try again. entity groups

### ISSUE THREAD

**Issue by sharkannon** [sonatype-nexus-community/nexus-blobstore-google-cloud#105]
We have a bunch of warnings to run a compact task on a few of our hosted repositories, but any time we try to, we get an exception.  From reading a little about this, we may be trying to run to many simultaneous threads when trying to do this compact, and over tasking the limits of the cloud stores.

```
2021-11-03 01:32:19,054+0000 ERROR [periodic-9-thread-1] *SYSTEM org.sonatype.nexus.scheduling.internal.PeriodicJobServiceImpl - Periodic job threw exception
com.google.cloud.datastore.DatastoreException: too much contention on these datastore entities. please try again. entity groups: [(app=REDACTED!blobstore-snapshots-blob-store, Sonatype, "Nexus Repository Manager")]
    at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:128)
    at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:154)
    at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496)
    at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493)
    at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
    at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
    at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
    at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:492)
    at com.google.cloud.datastore.TransactionImpl.commit(TransactionImpl.java:108)
    at org.sonatype.nexus.blobstore.gcloud.internal.ShardedCounterMetricsStore.flush(ShardedCounterMetricsStore.java:305)
    at org.sonatype.nexus.blobstore.gcloud.internal.GoogleCloudBlobStore.lambda$7(GoogleCloudBlobStore.java:194)
    at org.sonatype.nexus.scheduling.internal.PeriodicJobServiceImpl.lambda$1(PeriodicJobServiceImpl.java:90)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.datastore.v1.client.DatastoreException: too much contention on these datastore entities. please try again. entity groups: [(app=REDACTED!blobstore-snapshots-blob-store, Sonatype, "Nexus Repository Manager")]
    at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
    at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
    at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
    at com.google.datastore.v1.client.Datastore.commit(Datastore.java:87)
    at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152)
    ... 17 common frames omitted
```
Nexus version 3.34.1 (This is not new, been happening a VERY long time)
Nexus Blobstore Plugin: 0.34.0

* **What are you trying to do?**
Run a compact task on a google managed store.

* **What feature or behavior is this required for?**
Cleanup tasks

* **How could we solve this issue? (Not knowing is okay!)**
Not sure
* **Anything else?**

**Comment by nblair** [comment]
Thanks for the report - I'll have to try to replicate locally. Any guidance or input about your repository and blobstore setup (number of repos, number of blobstores, respective sizes, etc) would be appreciated!

**Comment by sharkannon** [comment]
I think the issue has to do with maybe how many items are in there.  Snapshot blobstore as seen in the image here.
(Sorry I didn't reply sooner, didn't get a message saying I had a reply)

![Screen Shot 2021-11-17 at 2 24 07 PM](https://user-images.githubusercontent.com/704223/142292179-41663cae-26d9-48b4-a417-709b1e3814a9.png)
e?

**Comment by sharkannon** [comment]
as for the number of blob stores.. we have about 12 total, and 4 of them are reporting issues.. the largest is the one above, the smalles
![Screen Shot 2021-11-17 at 2 27 58 PM](https://user-images.githubusercontent.com/704223/142292600-3e9c8cdb-bdbe-43cc-b0a3-1ae10ed91c63.png)
t

**Comment by sharkannon** [comment]
This is the error on the status page I'm seeing, but can't get rid of it because of the errors above.

![Screen Shot 2021-11-17 at 2 31 08 PM](https://user-images.githubusercontent.com/704223/142292960-85200847-316d-46ec-b173-c5d8cc779c93.png)

**Comment by nblair** [comment]
That's helpful @sharkannon - thanks! I have a sense of where the error is occurring. I think I need to build some backoff logic in how changes to the datastore are flushed out.

**Comment by sharkannon** [comment]
NP, let me know if. you need anything else, I check back once in a while (I tend to filter github to a folder and forget to check it lol)

**Comment by nblair** [comment]
I'm having an awful time trying to replicate this. I don't understand why https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/blob/main/nexus-blobstore-google-cloud/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/ShardedCounterMetricsStore.java#L267 can throw `DatastoreException: too much contention on these datastore entities`. There are at most 47 entities in that namespace, far below the limits per the documentation (https://cloud.google.com/datastore/docs/concepts/limits).

Can you turn on debug logging for `org.sonatype.nexus.blobstore.gcloud.internal.ShardedCounterMetricsStore`? I'd like to see the output. If possible, exporting the entities of the `MetricsStoreShard` in the datastore would be very helpful (there is no sensitive information in there, just counts across a number of shards, no IDs).

**Comment by sharkannon** [comment]
Debug Log from starting a compact task till the exception.

[debug.log](https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/files/7663034/debug.log)

**Comment by nblair** [comment]
Hi @sharkannon, thanks for the details that was helpful. I have a better idea of what is going on, but the bad news is I still don't have a fix. I'm going to enhance some of the logging for the next release, and a small fix to preserve these metrics deltas when the error occurs. I think the frequency of writes you experience is showing that I need to redesign how this mechanism adheres to the datastore limits.

**Comment by nblair** [comment]
I pushed up 9b1646cf72 to improve logging around this scenario; the commit is available in both 0.36.2 and 0.37.0 versions of the plugin. If you can upgrade your deployment and capture debug logs again that would be appreciated - thanks!

**Comment by sharkannon** [comment]
I've upgraded to 3.37.3 and 0.37.0 of the plugin, the numbers in the status are a bit larger 

```
snapshots-blob-store has 100000 soft-deleted blobs awaiting compaction
pypi-blob-store has 3260 soft-deleted blobs awaiting compaction
centos-base-storage has 100000 soft-deleted blobs awaiting compaction
packages-cloud-google-com has 1183 soft-deleted blobs awaiting compaction
```

And the logs show that they are not stopping at 1000 anymore.. (blobstore.compact-20220106201212583.log).. That being said, with 100000 blobs to be compacted or more.. that could take a VERY VERY long time aka over a year.. so this may not be a good thing :(

**Comment by sharkannon** [comment]
(took about 10 mins/1000 blobs)

**Comment by nblair** [comment]
100,000 is the self-imposed limit on the query against that table; I didn't want to leave it unbounded in the event there is some astronomical number is in there (don't want to run into possible JVM heap exhaustion or limitless running queries). It's likely you have far more than 100,000 soft-deleted blobs to remove for those blobstores 😬 . It will stay showing 100,000 for each of those blobstores until the query starts returning less. 

Thanks for upgrading and keeping me in the loop, I'll keep my 🤞

**Comment by sharkannon** [comment]
The two blob stores that are sub 100000 seem to be cleaning themselves up nicely.  it's the 2 100000 ones that will cause the problems.

**Comment by sharkannon** [comment]
Though I have noticed the exception in the logs, but the cleanup is still happening.

```
2022-01-07 05:46:16,530+0000 ERROR [periodic-9-thread-1]  *SYSTEM org.sonatype.nexus.scheduling.internal.PeriodicJobServiceImpl - Periodic job threw exception
com.google.cloud.datastore.DatastoreException: too much contention on these datastore entities. please try again. entity groups: [(app=m~xmatters-eng-build!blobstore-pypi-blob-store, Sonatype, "Nexus Repository Manager")]
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:128)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:154)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:492)
	at com.google.cloud.datastore.TransactionImpl.commit(TransactionImpl.java:108)
	at org.sonatype.nexus.blobstore.gcloud.internal.ShardedCounterMetricsStore.flush(ShardedCounterMetricsStore.java:322)
	at org.sonatype.nexus.blobstore.gcloud.internal.GoogleCloudBlobStore.lambda$7(GoogleCloudBlobStore.java:219)
	at org.sonatype.nexus.scheduling.internal.PeriodicJobServiceImpl.lambda$1(PeriodicJobServiceImpl.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.datastore.v1.client.DatastoreException: too much contention on these datastore entities. please try again. entity groups: [(app=m~xmatters-eng-build!blobstore-pypi-blob-store, Sonatype, "Nexus Repository Manager")]
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
	at com.google.datastore.v1.client.Datastore.commit(Datastore.java:87)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152)
	... 17 common frames omitted
```

**Comment by sharkannon** [comment]
So, I think I see the "issue" that's been happening.  It's not the exception or the like that is the actual problem, it's the "limit" you have in place 

> 100,000 is the self-imposed limit on the query against that table; 

it appears that it'll clean up to that specific ammount and then stop cleaning (assuming that it's done?), when it was at 1000 before, I guess it would have eventually fixed itself, but it looks like I may have had over 1000000 records in there, so I don't know if it would have ever caught up.  It's now down to 64k, which I'm assumning it'll finish up with today (in the snapshots repo, which is all that's showing now).

Not sure if you can "fix" that or not, but may be somethign worth noting.

**Comment by nblair** [comment]
Right, that limit was a bit of a design choice and a shortest path forward. I'd rather have the task finish, even if incomplete, rather than running for an indefinite amount of time with no UX for the administrator to have a sense of when it will end or to stop it prematurely. The limit is big enough (I think) to cover most cases. If I see that limit coming up regularly in issues I'll look into making it configurable.

**Comment by sharkannon** [comment]
Ok.. well I think this is now resolved, going to close out the ticket, thanks for the help.
