### ISSUE TITLE
ITs are DOA / broken / platform dependant or are missing some details on how to run them

### ISSUE THREAD

**Issue by jtnord** [sonatype-nexus-community/nexus-blobstore-google-cloud#129]
* **What are you trying to do?**

Build the latest version, and ensure test pass before making any contribution

* **What feature or behaviour is this required for?**

Any and every community contribution

* **How could we solve this issue? (Not knowing is okay!)**

ITs should never be failing on the mainline branch.

* **Anything else?**

they are not run as part of CI either (#128 )

`KarafTestContainer` fails to start, causing test timeout.

```
2024-11-01 15:40:15,804+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.pax.logging.NexusLogActivator - start
2024-11-01 15:40:17,818+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.features.internal.FeaturesWrapper - Fast FeaturesService starting
2024-11-01 15:40:18,468+0000 WARN  [FelixStartLevel] *SYSTEM org.ops4j.pax.url.mvn.internal.AetherBasedResolver - Error resolving artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01: [Could not find artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01]
java.io.IOException: Error resolving artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01: [Could not find artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
 ...
```

```
2024-11-01 15:40:18,469+0000 ERROR [FelixStartLevel] *SYSTEM org.apache.karaf.features.internal.service.BootFeaturesInstaller - Error installing boot feature repository mvn:org.sonatype.nexus.testsuite/nexus-repository-content-testsupport/3.62.0-01/xml/features
java.lang.RuntimeException: Error resolving artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01: [Could not find artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01] : mvn:org.sonatype.nexus.testsuite/nexus-repository-content-testsupport/3.62.0-01/xml/features
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:121)
        at org.apache.karaf.features.internal.service.RepositoryImpl.<init>(RepositoryImpl.java:51)
        at org.apache.karaf.features.internal.service.RepositoryCacheImpl.create(RepositoryCacheImpl.java:51)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.addRepository(FeaturesServiceImpl.java:386)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.addRepository(FeaturesServiceImpl.java:381)
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.addRepositories(BootFeaturesInstaller.java:136)
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.installBootFeatures(BootFeaturesInstaller.java:95)
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.start(BootFeaturesInstaller.java:89)
        at org.apache.karaf.features.internal.osgi.Activator.doStart(Activator.java:215)
        at org.apache.karaf.util.tracker.BaseActivator.start(BaseActivator.java:92)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Error resolving artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01: [Could not find artifact org.sonatype.nexus.testsuite:nexus-repository-content-testsupport:xml:features:3.62.0-01]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
        at org.ops4j.pax.url.mvn.internal.
...
```

Maven 3.9.7
java 1.8.0_432

Steps to reproduce.

```
gcloud init
gcloud auth application-default login
export GOOGLE_APPLICATION_CREDENTIALS=~/.config/gcloud/application_default_credentials.json
mvn verify
```

**Comment by nblair** [comment]
See #128

**Comment by madpah** [comment]
ℹ️ As of 7th November 2024, this community project has [graduated](https://contribute.sonatype.com/docs/project-classification/) and is offered as part of Sonatype's commercial offerings - see [here](https://help.sonatype.com/en/configuring-blob-stores.html#google-cloud-blob-store) for full details.

🚧 This community project will receive not accept further contributions nor receive maintenance.
