### ISSUE TITLE
NXRM 3.16 fails to start with 0.5.0 release

### ISSUE THREAD

**Issue by nblair** [sonatype-nexus-community/nexus-blobstore-google-cloud#31]
Plugin correctly installed, but NXRM 3.16 fails to start with:

```
Caused by: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-core-feature; type=karaf.feature; version=0; filter:="(&(osgi.identity=nexus-core-feature)(type=karaf.feature)(version>=0.0.0))" [caused by: Unable to resolve nexus-core-feature/3.17.0.SNAPSHOT: missing requirement [nexus-core-feature/3.17.0.SNAPSHOT] osgi.identity; osgi.identity=nexus-blobstore-google-cloud; type=karaf.feature; version="[0.6.0.SNAPSHOT,0.6.0.SNAPSHOT]" [caused by: Unable to resolve nexus-blobstore-google-cloud/0.6.0.SNAPSHOT: missing requirement [nexus-blobstore-google-cloud/0.6.0.SNAPSHOT] osgi.identity; osgi.identity=com.google.http-client.google-http-client; type=osgi.bundle; version="[1.29.0,1.29.0]"; resolution:=mandatory [caused by: Unable to resolve com.google.http-client.google-http-client/1.29.0: missing requirement [com.google.http-client.google-http-client/1.29.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.google.common.base)(version>=26.0.0)(!(version>=27.0.0)))"]]]
        at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:259)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nblair** [comment]
Fixed in the 0.5.1 release.
